### ISSUE TITLE
Got an answer for this one?

### ISSUE THREAD

**Issue by jodonnell-broadsoft** [aliang/google_contacts_api#10]
http://stackoverflow.com/questions/31151310/what-is-the-id-of-the-starred-contacts-group-in-the-google-contacts-api

I can't seem to get the contacts in the starred group. Will your library do that?

Thanks @aliang

**Comment by aliang** [comment]
Yes, you can get it using this library. The starred group appears to be a first-class group object. When I starred some contacts from the web interface (via Gmail), I got a new group called "Starred in Android". (However, I don't know if the name 'Starred in Android' is something you can rely on not to change over time.)

Here is the code I used (some output hidden for privacy):

````ruby
user = GoogleContactsApi::User.new(token)
g = user.groups.find { |g| g.title == 'Starred in Android' }
g.id # => http://www.google.com/m8/feeds/groups/<account email address>/base/<hex string>
g.contacts.first # => <GoogleContactsApi::Contact: Starred Contact Name>
````
