### ISSUE TITLE
uninitialized constant Api::TransactionController::GoogleContactsApi

### ISSUE THREAD

**Issue by xishoon** [aliang/google_contacts_api#23]
I am getting following error

`uninitialized constant Api::TransactionController::GoogleContactsApi
`

 when i try to initiliaze the constructor
      

`google_contacts_user = GoogleContactsApi::User.new(oauth_access_token_for_user)
`

**Comment by aliang** [comment]
This is a problem with namespacing. Try placing two colons in front, i.e.

`::GoogleContactsApi::User.new(...)`

**Comment by xishoon** [comment]
I added the two colons but now its giving me the following error
`uninitialized constant GoogleContactsApi`

**Comment by aliang** [comment]
It looks like you need to require or load the `google_contacts_api` library properly in your app. I cannot provide any further assistance here since this does not appear to be a problem caused by the library.
